version: "3.8"
services:
  app:
    container_name: chatbotto
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev
